# Generated by Django 3.2.10 on 2022-01-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0024_remove_servicedetail_text_on_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Раздел "Статьи"',
                'verbose_name_plural': 'Раздел "Статьи"',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('is_activated', models.BooleanField(default=True)),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Статья к отдельной услуге',
                'verbose_name_plural': 'Статьи к отдельной услуге',
            },
        ),
    ]
