# Generated by Django 3.2.10 on 2022-01-09 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name': 'Статья по теме', 'verbose_name_plural': 'Статьи по темам'},
        ),
        migrations.AddField(
            model_name='articledetail',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='articlelist',
            name='text',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Описание раздела'),
        ),
        migrations.AlterField(
            model_name='articlelist',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок раздела'),
        ),
    ]
