# Generated by Django 3.2.10 on 2022-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220109_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение для статьи'),
        ),
    ]
