# Generated by Django 3.2.10 on 2022-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articledetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
