# Generated by Django 3.2.10 on 2022-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articledetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
