# Generated by Django 3.2.10 on 2022-01-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0024_remove_servicedetail_text_on_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=150, verbose_name='Пункт прайс-листа')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicedetail')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
    ]
