# Generated by Django 3.2.10 on 2022-01-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_auto_20220113_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item_1',
            new_name='item',
        ),
    ]
