# Generated by Django 3.2.10 on 2022-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_rename_item_1_price_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item',
            new_name='item_1',
        ),
    ]
