# Generated by Django 3.2.10 on 2022-01-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=50, verbose_name='Страница сайта')),
            ],
            options={
                'verbose_name': '   Страница сайта',
                'verbose_name_plural': '   Страницы сайта',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение для статьи')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_activated', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zamki.page')),
            ],
            options={
                'verbose_name': '   Статья',
                'verbose_name_plural': '   Статьи',
            },
        ),
    ]
