# Generated by Django 3.2.10 on 2022-01-13 08:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('viber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Вайбер')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': '       Контактные данные',
                'verbose_name_plural': '       Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, max_length=300, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение, заказ',
                'verbose_name_plural': 'Сообщения, заказы',
            },
        ),
    ]
