# Generated by Django 3.2.10 on 2022-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, max_length=500, verbose_name='Сообщение'),
        ),
    ]
