# Generated by Django 3.2.10 on 2022-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title страницы')),
                ('text_on_photo', models.CharField(blank=True, max_length=120, verbose_name='Текст на фото')),
            ],
            options={
                'verbose_name': 'Общие данные',
                'verbose_name_plural': 'Общие данные',
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название услуги')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото услуги')),
                ('text', models.CharField(blank=True, max_length=120, verbose_name='Текст под фото')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
