# Generated by Django 3.2.10 on 2022-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceList',
            new_name='Service',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название статьи'),
        ),
    ]
