# Generated by Django 3.2.10 on 2022-01-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220105_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageInfo',
        ),
    ]
