# Generated by Django 3.2.10 on 2022-01-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220105_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceDetail',
        ),
    ]
