# Generated by Django 3.2.10 on 2022-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_service_servicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='image',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_big',
            field=models.FileField(blank=True, upload_to='', verbose_name='Большое фото'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image_little',
            field=models.FileField(blank=True, upload_to='', verbose_name='Малое фото'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='text_on_image',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст на маленьком фото'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='text_under_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст под маленьком фото'),
        ),
    ]
