# Generated by Django 3.2.10 on 2022-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20220105_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
