# Generated by Django 3.2.10 on 2022-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicedetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
