# Generated by Django 3.2.10 on 2022-01-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_servicedetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='slug',
        ),
    ]
