# Generated by Django 3.2.10 on 2022-01-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_servicedetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
