# Generated by Django 3.2.10 on 2022-01-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_servicedetail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.RenameModel(
            old_name='ServiceArticle',
            new_name='ServiceDetailArticle',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text_under_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст под маленьким фото'),
        ),
    ]
