# Generated by Django 3.2.10 on 2022-01-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20220105_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='text',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text_under_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст под фото на "Services"'),
        ),
    ]
