# Generated by Django 3.2.10 on 2022-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20220106_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetailarticle',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicelistarticle',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
