# Generated by Django 3.2.10 on 2022-01-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20220106_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Список услуг'},
        ),
        migrations.AlterModelOptions(
            name='servicedetailarticle',
            options={'verbose_name': 'Статья к отдельной услуге', 'verbose_name_plural': 'Статьи к отдельной услуге'},
        ),
        migrations.AlterModelOptions(
            name='servicelistarticle',
            options={'verbose_name': 'Статья к разделу "Услуги"', 'verbose_name_plural': 'Статьи к разделу "Услуги"'},
        ),
    ]
