# Generated by Django 3.2.10 on 2022-01-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_servicedetailarticle_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetailarticle',
            name='service',
        ),
        migrations.AddField(
            model_name='servicedetailarticle',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.servicedetail', verbose_name='Услуга'),
        ),
    ]
