# Generated by Django 3.2.10 on 2022-01-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_rename_name_servicedetailarticle_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetailarticle',
            old_name='service',
            new_name='name',
        ),
    ]
