# Generated by Django 3.2.10 on 2022-01-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_rename_service_servicedetailarticle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetail',
            old_name='name',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='servicedetailarticle',
            old_name='name',
            new_name='service',
        ),
    ]
