# Generated by Django 3.2.10 on 2022-01-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20220108_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='text_on_image',
        ),
    ]
