# Generated by Django 3.2.10 on 2022-11-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_remove_servicedetail_text_on_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': '  Услуга', 'verbose_name_plural': '   Список услуг'},
        ),
        migrations.AlterModelOptions(
            name='servicelistarticle',
            options={'verbose_name': ' Статья к разделу "Услуги"', 'verbose_name_plural': ' Статьи к разделу "Услуги"'},
        ),
    ]
