# Generated by Django 3.2.10 on 2022-01-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название раздела')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Текст, до 200 зн.')),
            ],
            options={
                'verbose_name': 'Название раздела',
                'verbose_name_plural': 'Текст о компании',
            },
        ),
    ]
