# Generated by Django 3.2.10 on 2022-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=120, verbose_name='Текст, до 120 зн.')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Принцип работы',
                'verbose_name_plural': 'Принципы работы',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Раздел "О компании"', 'verbose_name_plural': 'Раздел "О компании"'},
        ),
    ]
