# Generated by Django 3.2.10 on 2022-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homearticlewithphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticlewithphoto',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение для статьи'),
        ),
    ]
