# Generated by Django 3.2.10 on 2022-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homearticlewithphoto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '      Раздел "О компании"', 'verbose_name_plural': '      Раздел "О компании"'},
        ),
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': '       Верхняя часть с фото', 'verbose_name_plural': '       Верхняя часть с фото'},
        ),
        migrations.AlterModelOptions(
            name='homearticle',
            options={'verbose_name': '  Статья без фото', 'verbose_name_plural': '  Статьи без фото'},
        ),
        migrations.AlterModelOptions(
            name='homearticlewithphoto',
            options={'verbose_name': '   Статья с фото', 'verbose_name_plural': '   Статьи с фото'},
        ),
        migrations.AlterModelOptions(
            name='principle',
            options={'verbose_name': '     Принцип работы', 'verbose_name_plural': '     Принципы работы'},
        ),
        migrations.AlterModelOptions(
            name='videoblock',
            options={'verbose_name': '    Блок с видео', 'verbose_name_plural': '    Блок с видео'},
        ),
        migrations.AddField(
            model_name='homearticle',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
