# Generated by Django 3.2.10 on 2022-01-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220106_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeArticle',
        ),
        migrations.DeleteModel(
            name='HomeArticleWithPhoto',
        ),
    ]
