# Generated by Django 3.2.10 on 2022-01-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220107_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '  Статья без фото',
                'verbose_name_plural': '  Статьи без фото',
            },
        ),
        migrations.CreateModel(
            name='HomeArticleWithPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('text', models.CharField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение для статьи')),
            ],
            options={
                'verbose_name': '   Статья с фото',
                'verbose_name_plural': '   Статьи с фото',
            },
        ),
    ]
